### ISSUE TITLE
Unsupported Media Type error on publish

### ISSUE THREAD

**Issue by Amelus** [aepfli/gradle-gitlab-repositories#1]
`> Task :publishCommercePublicationToGitLabRepository FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':publishCommercePublicationToGitLabRepository'.
> Failed to publish publication 'Commerce' to repository 'GitLab'
   > Could not PUT 'someNiceUrl/3.7.0-SNAPSHOT/maven-metadata.xml'. Received status code 415 from server: Unsupported Media Type
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org`

Good luck fixing :D

**Comment by aepfli** [comment]
After close investigation i found the error in a missconception within the plugin.

It is not possible to release to a group with the plugin. Therefor upload needs to be defined for a project! which you actually did, but the endpoint was a wrong one.

Pull request will be opened soon, with including tests
