### ISSUE TITLE
How to specify custom Gitlab URL?

### ISSUE THREAD

**Issue by leodotcloud** [aepfli/gradle-gitlab-repositories#47]
If I were using a private/custom intallation of Gitlab, how do I configure the plugin to change the URL from `gitlab.com` to `gitlab.example.com`?

**Comment by aepfli** [comment]
there is an undocumented property called `baseurl` which is currently set to `gitlab.com`

the groovy dsl approach would look like this:
```groovy
gitLab {
    baseUrl = "gitlab.example.com" 
}
```

**Comment by aepfli** [comment]
as there was no  further question, i will close this issue
