### ISSUE TITLE
Question: Is it possible configure repositories in `pluginManagement` block?

### ISSUE THREAD

**Issue by piotrminkina** [aepfli/gradle-gitlab-repositories#73]
Hello,

I have private Maven Repository of Gradle Plugins on Gitlab. I would like configure `pluginManagement` block to access to this repository. Is it possible via your plugin?

Regards
Piotr Minkina

**Comment by aepfli** [comment]
First of all, sorry for the late reply - that is definitley not how it should be.

Yes it should be possible

**Comment by piotrminkina** [comment]
@aepfli Hi, no problem. I, for one, seem to have forgotten what problems I had at that time :D. Anyway, I use your plugin successfully in both `settings.gradle` and `build.gradle`. I created a file `gradle/repositories.gradle`, which I attach using `apply from:`, and in the file itself I recognize the context and I configure `pluginManagement.repositories` or `repositories`. It works as needed. Thanks for your work!
